// Generated by Style Dictionary. Do not edit.
import SwiftUI

public extension Color {
    /// Initialize a Color from a hex string (#RRGGBB or #RRGGBBAA)
    init(hex: String) {
        let cleaned = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        let scanner = Scanner(string: cleaned)
        var hexNumber: UInt64 = 0
        guard scanner.scanHexInt64(&hexNumber) else {
            self = .clear
            return
        }

        let r, g, b, a: Double
        switch cleaned.count {
        case 6:
            r = Double((hexNumber & 0xFF0000) >> 16) / 255.0
            g = Double((hexNumber & 0x00FF00) >> 8) / 255.0
            b = Double(hexNumber & 0x0000FF) / 255.0
            a = 1.0
        case 8:
            r = Double((hexNumber & 0xFF000000) >> 24) / 255.0
            g = Double((hexNumber & 0x00FF0000) >> 16) / 255.0
            b = Double((hexNumber & 0x0000FF00) >> 8) / 255.0
            a = Double(hexNumber & 0x000000FF) / 255.0
        default:
            self = .clear
            return
        }

        self = Color(.sRGB, red: r, green: g, blue: b, opacity: a)
    }
}
