// Generated by Style Dictionary. Do not edit.
import SwiftUI

public enum ThemeId: String, CaseIterable, Codable {
    case bulmaLight = "bulma-light"
    case bulmaDark = "bulma-dark"
    case catppuccinLatte = "catppuccin-latte"
    case catppuccinFrappe = "catppuccin-frappe"
    case catppuccinMacchiato = "catppuccin-macchiato"
    case catppuccinMocha = "catppuccin-mocha"
    case dracula = "dracula"
    case githubLight = "github-light"
    case githubDark = "github-dark"
}

public enum ThemeAppearance: String {
    case light
    case dark
}

public struct ThemePalette: Equatable {
    public let backgroundBase: Color
    public let backgroundSurface: Color
    public let backgroundOverlay: Color
    public let textPrimary: Color
    public let textSecondary: Color
    public let textInverse: Color
    public let brandPrimary: Color
    public let stateInfo: Color
    public let stateSuccess: Color
    public let stateWarning: Color
    public let stateDanger: Color
    public let borderDefault: Color
    public let accentLink: Color
    public let headingH1: Color
    public let headingH2: Color
    public let headingH3: Color
    public let headingH4: Color
    public let headingH5: Color
    public let headingH6: Color
    public let bodyPrimary: Color
    public let bodySecondary: Color
    public let linkDefault: Color
    public let selectionFg: Color
    public let selectionBg: Color
    public let blockquoteBorder: Color
    public let blockquoteFg: Color
    public let blockquoteBg: Color
    public let codeInlineFg: Color
    public let codeInlineBg: Color
    public let codeBlockFg: Color
    public let codeBlockBg: Color
    public let tableBorder: Color
    public let tableStripe: Color
    public let tableTheadBg: Color
    public let tableCellBg: Color?
    public let tableHeaderFg: Color?

    public init(backgroundBase: Color, backgroundSurface: Color, backgroundOverlay: Color, textPrimary: Color, textSecondary: Color, textInverse: Color, brandPrimary: Color, stateInfo: Color, stateSuccess: Color, stateWarning: Color, stateDanger: Color, borderDefault: Color, accentLink: Color, headingH1: Color, headingH2: Color, headingH3: Color, headingH4: Color, headingH5: Color, headingH6: Color, bodyPrimary: Color, bodySecondary: Color, linkDefault: Color, selectionFg: Color, selectionBg: Color, blockquoteBorder: Color, blockquoteFg: Color, blockquoteBg: Color, codeInlineFg: Color, codeInlineBg: Color, codeBlockFg: Color, codeBlockBg: Color, tableBorder: Color, tableStripe: Color, tableTheadBg: Color, tableCellBg: Color?, tableHeaderFg: Color?) {
        self.backgroundBase = backgroundBase
        self.backgroundSurface = backgroundSurface
        self.backgroundOverlay = backgroundOverlay
        self.textPrimary = textPrimary
        self.textSecondary = textSecondary
        self.textInverse = textInverse
        self.brandPrimary = brandPrimary
        self.stateInfo = stateInfo
        self.stateSuccess = stateSuccess
        self.stateWarning = stateWarning
        self.stateDanger = stateDanger
        self.borderDefault = borderDefault
        self.accentLink = accentLink
        self.headingH1 = headingH1
        self.headingH2 = headingH2
        self.headingH3 = headingH3
        self.headingH4 = headingH4
        self.headingH5 = headingH5
        self.headingH6 = headingH6
        self.bodyPrimary = bodyPrimary
        self.bodySecondary = bodySecondary
        self.linkDefault = linkDefault
        self.selectionFg = selectionFg
        self.selectionBg = selectionBg
        self.blockquoteBorder = blockquoteBorder
        self.blockquoteFg = blockquoteFg
        self.blockquoteBg = blockquoteBg
        self.codeInlineFg = codeInlineFg
        self.codeInlineBg = codeInlineBg
        self.codeBlockFg = codeBlockFg
        self.codeBlockBg = codeBlockBg
        self.tableBorder = tableBorder
        self.tableStripe = tableStripe
        self.tableTheadBg = tableTheadBg
        self.tableCellBg = tableCellBg
        self.tableHeaderFg = tableHeaderFg
    }
}

public struct ThemeDefinition: Identifiable, Equatable {
    public let id: ThemeId
    public let label: String
    public let vendor: String
    public let appearance: ThemeAppearance
    public let palette: ThemePalette

    public init(
        id: ThemeId,
        label: String,
        vendor: String,
        appearance: ThemeAppearance,
        palette: ThemePalette
    ) {
        self.id = id
        self.label = label
        self.vendor = vendor
        self.appearance = appearance
        self.palette = palette
    }
}
