// SPDX-License-Identifier: MIT
/**
 * Style Dictionary configuration for Swift (iOS + macOS).
 *
 * Input: dist/tokens/style-dictionary/themes.json (generated by prepare-style-dictionary.mjs)
 * Output: dist/swift/*.swift (to be consumed by turbo-notes-apple)
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import baseConfig from './style-dictionary.config.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const autoHeader = '// Generated by Style Dictionary. Do not edit.';

const paletteProps = [
  { name: 'backgroundBase', path: ['color', 'background', 'base'] },
  { name: 'backgroundSurface', path: ['color', 'background', 'surface'] },
  { name: 'backgroundOverlay', path: ['color', 'background', 'overlay'] },
  { name: 'textPrimary', path: ['color', 'text', 'primary'] },
  { name: 'textSecondary', path: ['color', 'text', 'secondary'] },
  { name: 'textInverse', path: ['color', 'text', 'inverse'] },
  { name: 'brandPrimary', path: ['color', 'brand', 'primary'] },
  { name: 'stateInfo', path: ['color', 'state', 'info'] },
  { name: 'stateSuccess', path: ['color', 'state', 'success'] },
  { name: 'stateWarning', path: ['color', 'state', 'warning'] },
  { name: 'stateDanger', path: ['color', 'state', 'danger'] },
  { name: 'borderDefault', path: ['color', 'border', 'default'] },
  { name: 'accentLink', path: ['color', 'accent', 'link'] },
  { name: 'headingH1', path: ['content', 'heading', 'h1'] },
  { name: 'headingH2', path: ['content', 'heading', 'h2'] },
  { name: 'headingH3', path: ['content', 'heading', 'h3'] },
  { name: 'headingH4', path: ['content', 'heading', 'h4'] },
  { name: 'headingH5', path: ['content', 'heading', 'h5'] },
  { name: 'headingH6', path: ['content', 'heading', 'h6'] },
  { name: 'bodyPrimary', path: ['content', 'body', 'primary'] },
  { name: 'bodySecondary', path: ['content', 'body', 'secondary'] },
  { name: 'linkDefault', path: ['content', 'link', 'default'] },
  { name: 'selectionFg', path: ['content', 'selection', 'fg'] },
  { name: 'selectionBg', path: ['content', 'selection', 'bg'] },
  { name: 'blockquoteBorder', path: ['content', 'blockquote', 'border'] },
  { name: 'blockquoteFg', path: ['content', 'blockquote', 'fg'] },
  { name: 'blockquoteBg', path: ['content', 'blockquote', 'bg'] },
  { name: 'codeInlineFg', path: ['content', 'codeInline', 'fg'] },
  { name: 'codeInlineBg', path: ['content', 'codeInline', 'bg'] },
  { name: 'codeBlockFg', path: ['content', 'codeBlock', 'fg'] },
  { name: 'codeBlockBg', path: ['content', 'codeBlock', 'bg'] },
  { name: 'tableBorder', path: ['content', 'table', 'border'] },
  { name: 'tableStripe', path: ['content', 'table', 'stripe'] },
  { name: 'tableTheadBg', path: ['content', 'table', 'theadBg'] },
  { name: 'tableCellBg', path: ['content', 'table', 'cellBg'], optional: true },
  { name: 'tableHeaderFg', path: ['content', 'table', 'headerFg'], optional: true },
];

const optionalProps = new Set(
  paletteProps.filter((p) => p.optional).map((p) => p.name)
);

const toCamel = (id) =>
  id
    .split(/[-_]/g)
    .map((chunk, index) =>
      index === 0
        ? chunk.toLowerCase()
        : chunk.charAt(0).toUpperCase() + chunk.slice(1).toLowerCase()
    )
    .join('');

const getTokenValue = (theme, pathParts) =>
  pathParts.reduce((acc, key) => (acc && acc[key] ? acc[key] : undefined), theme)
    ?.value;

function escapeSwiftString(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

StyleDictionary.registerFormat({
  name: 'swift/btt-colors',
  format() {
    return `${autoHeader}\nimport SwiftUI\n\npublic extension Color {\n    /// Initialize a Color from a hex string (#RRGGBB or #RRGGBBAA)\n    init(hex: String) {\n        let cleaned = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))\n        let scanner = Scanner(string: cleaned)\n        var hexNumber: UInt64 = 0\n        guard scanner.scanHexInt64(&hexNumber) else {\n            self = .clear\n            return\n        }\n\n        let r, g, b, a: Double\n        switch cleaned.count {\n        case 6:\n            r = Double((hexNumber & 0xFF0000) >> 16) / 255.0\n            g = Double((hexNumber & 0x00FF00) >> 8) / 255.0\n            b = Double(hexNumber & 0x0000FF) / 255.0\n            a = 1.0\n        case 8:\n            r = Double((hexNumber & 0xFF000000) >> 24) / 255.0\n            g = Double((hexNumber & 0x00FF0000) >> 16) / 255.0\n            b = Double((hexNumber & 0x0000FF00) >> 8) / 255.0\n            a = Double(hexNumber & 0x000000FF) / 255.0\n        default:\n            self = .clear\n            return\n        }\n\n        self = Color(.sRGB, red: r, green: g, blue: b, opacity: a)\n    }\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'swift/btt-theme-types',
  format({ dictionary }) {
    const themes = dictionary.tokens.themes || {};
    const themeIds = Object.keys(themes);

    const enumCases = themeIds
      .map((id) => `    case ${toCamel(id)} = "${id}"`)
      .join('\n');

    const appearanceEnum = `public enum ThemeAppearance: String {\n    case light\n    case dark\n}\n`;

    const paletteStruct = `public struct ThemePalette: Equatable {\n${paletteProps
      .map(
        (p) => `    public let ${p.name}: Color${optionalProps.has(p.name) ? '?' : ''}`
      )
      .join('\n')}\n\n    public init(${paletteProps
      .map((p) => `${p.name}: Color${optionalProps.has(p.name) ? '?' : ''}`)
      .join(', ')}) {\n${paletteProps
      .map((p) => `        self.${p.name} = ${p.name}`)
      .join('\n')}\n    }\n}\n`;

    const themeStruct = `public struct ThemeDefinition: Identifiable, Equatable {\n    public let id: ThemeId\n    public let label: String\n    public let vendor: String\n    public let appearance: ThemeAppearance\n    public let palette: ThemePalette\n\n    public init(\n        id: ThemeId,\n        label: String,\n        vendor: String,\n        appearance: ThemeAppearance,\n        palette: ThemePalette\n    ) {\n        self.id = id\n        self.label = label\n        self.vendor = vendor\n        self.appearance = appearance\n        self.palette = palette\n    }\n}\n`;

    return `${autoHeader}\nimport SwiftUI\n\npublic enum ThemeId: String, CaseIterable, Codable {\n${enumCases}\n}\n\n${appearanceEnum}\n${paletteStruct}\n${themeStruct}`;
  },
});

StyleDictionary.registerFormat({
  name: 'swift/btt-theme-registry',
  format({ dictionary }) {
    const themes = dictionary.tokens.themes || {};
    const themeEntries = Object.entries(themes);

    const themeInitLines = themeEntries.map(([id, theme]) => {
      const caseName = toCamel(id);
      const label = theme.meta?.label?.value ?? id;
      const vendor = theme.meta?.vendor?.value ?? 'unknown';
      const appearance = theme.meta?.appearance?.value === 'dark' ? '.dark' : '.light';

      const paletteArgs = paletteProps
        .map((p) => {
          const value = getTokenValue(theme, p.path);
          const isOptional = optionalProps.has(p.name);
          if (!value && isOptional) {
            return `            ${p.name}: nil`;
          }
          if (!value) {
            return `            ${p.name}: Color.clear`;
          }
          return `            ${p.name}: Color(hex: "${value}")`;
        })
        .join(',\n');

      return `        .${caseName}: ThemeDefinition(\n            id: .${caseName},\n            label: "${escapeSwiftString(label)}",\n            vendor: "${escapeSwiftString(vendor)}",\n            appearance: ${appearance},\n            palette: ThemePalette(\n${paletteArgs}\n            )\n        )`;
    });

    return `${autoHeader}\nimport SwiftUI\n\npublic enum ThemeRegistry {\n    public static let themes: [ThemeId: ThemeDefinition] = [\n${themeInitLines.join(',\n')}\n    ]\n\n    public static let ordered: [ThemeDefinition] = ThemeId.allCases.compactMap { themes[$0] }\n}\n`;
  },
});

const config = {
  ...baseConfig,
  platforms: {
    swift: {
      transformGroup: 'ios-swift',
      buildPath: path.join(__dirname, '..', 'dist', 'swift/'),
      files: [
        {
          destination: 'TurboThemeColors.swift',
          format: 'swift/btt-colors',
        },
        {
          destination: 'TurboTheme.swift',
          format: 'swift/btt-theme-types',
        },
        {
          destination: 'TurboThemeRegistry.swift',
          format: 'swift/btt-theme-registry',
        },
      ],
    },
  },
};

export default config;
